name = "routine"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB" 
database_name = "routineApp"
database_id = "df73bf62-462e-4cc7-b6db-3a6f5380583e"

[triggers]
crons = ["0 18 * * *"]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
FRONT_END_URL = 'https://routine-lemon.vercel.app' #http://localhost:5173

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

